@echo off
REM ****************************************************************************
REM Vivado (TM) v2026.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sat Oct 03 13:11:44 +0300 2026
REM SW Build 6511674 on Tue Jun 16 11:02:23 MDT 2026
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L microblaze_v11_0_17 -L axi_lite_ipif_v3_1_0 -L axi_timer_v2_0_38 -L interrupt_control_v3_2_0 -L axi_gpio_v2_0_38 -L lmb_v10_v3_0_16 -L lmb_bram_if_cntlr_v4_0_28 -L blk_mem_gen_v8_4_13 -L smartconnect_v1_0 -L proc_sys_reset_v5_0_17 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_37 -L axi_vip_v1_1_23 -L axi_intc_v4_1_23 -L mdm_v3_2_30 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot MicroBlaze_tb_behav xil_defaultlib.MicroBlaze_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L microblaze_v11_0_17 -L axi_lite_ipif_v3_1_0 -L axi_timer_v2_0_38 -L interrupt_control_v3_2_0 -L axi_gpio_v2_0_38 -L lmb_v10_v3_0_16 -L lmb_bram_if_cntlr_v4_0_28 -L blk_mem_gen_v8_4_13 -L smartconnect_v1_0 -L proc_sys_reset_v5_0_17 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_37 -L axi_vip_v1_1_23 -L axi_intc_v4_1_23 -L mdm_v3_2_30 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot MicroBlaze_tb_behav xil_defaultlib.MicroBlaze_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
