domain_path: D:/Learn/robotdreams/Homework_004/MicroBlaze/microblaze/export/microblaze/sw/standalone_microblaze_0
app_src_dir: D:\AMDdesign\2026.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
