# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MicroBlaze/MicroBlaze.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze || ORIG_REF_NAME==MicroBlaze} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_microblaze_0_0 || ORIG_REF_NAME==MicroBlaze_microblaze_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_clk_wiz_0_0/MicroBlaze_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_clk_wiz_0_0 || ORIG_REF_NAME==MicroBlaze_clk_wiz_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_axi_timer_0_0/MicroBlaze_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_axi_timer_0_0 || ORIG_REF_NAME==MicroBlaze_axi_timer_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_axi_gpio_0_0/MicroBlaze_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_axi_gpio_0_0 || ORIG_REF_NAME==MicroBlaze_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_dlmb_v10_0/MicroBlaze_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_dlmb_v10_0 || ORIG_REF_NAME==MicroBlaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_ilmb_v10_0/MicroBlaze_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_ilmb_v10_0 || ORIG_REF_NAME==MicroBlaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_dlmb_bram_if_cntlr_0/MicroBlaze_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_ilmb_bram_if_cntlr_0/MicroBlaze_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_lmb_bram_0/MicroBlaze_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_lmb_bram_0 || ORIG_REF_NAME==MicroBlaze_lmb_bram_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_microblaze_0_axi_periph_0/MicroBlaze_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MicroBlaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_microblaze_0_axi_intc_0/MicroBlaze_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MicroBlaze_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_mdm_1_0/MicroBlaze_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_mdm_1_0 || ORIG_REF_NAME==MicroBlaze_mdm_1_0} -quiet] -quiet

# IP: bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_0_100M_0/MicroBlaze_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==MicroBlaze_rst_clk_wiz_0_100M_0} -quiet] -quiet

# XDC: d:/Learn/robotdreams/Homework_004/MicroBlaze/MicroBlaze.gen/sources_1/bd/MicroBlaze/MicroBlaze_ooc.xdc
