# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout.xdc

# Block Designs: bd/zynq_PS/zynq_PS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_PS || ORIG_REF_NAME==zynq_PS} -quiet] -quiet

# IP: bd/zynq_PS/ip/zynq_PS_processing_system7_0_0/zynq_PS_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_PS_processing_system7_0_0 || ORIG_REF_NAME==zynq_PS_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_PS/ip/zynq_PS_axi_gpio_0_0/zynq_PS_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_PS_axi_gpio_0_0 || ORIG_REF_NAME==zynq_PS_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_PS/ip/zynq_PS_axi_timer_0_0/zynq_PS_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_PS_axi_timer_0_0 || ORIG_REF_NAME==zynq_PS_axi_timer_0_0} -quiet] -quiet

# IP: bd/zynq_PS/ip/zynq_PS_axi_smc_0/zynq_PS_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_PS_axi_smc_0 || ORIG_REF_NAME==zynq_PS_axi_smc_0} -quiet] -quiet

# IP: bd/zynq_PS/ip/zynq_PS_rst_ps7_0_50M_0/zynq_PS_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_PS_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_PS_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/Learn/robotdreams/Homework_004/Zynq_PS/Zynq_PS.gen/sources_1/bd/zynq_PS/zynq_PS_ooc.xdc
