# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Learn/robotdreams/Homework_004/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_mdm_1_0/MicroBlaze_mdm_1_0.xci
# IP: The module: 'MicroBlaze_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Learn/robotdreams/Homework_004/MicroBlaze/MicroBlaze.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_mdm_1_0/MicroBlaze_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Learn/robotdreams/Homework_004/MicroBlaze/MicroBlaze.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_mdm_1_0/MicroBlaze_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Learn/robotdreams/Homework_004/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_mdm_1_0/MicroBlaze_mdm_1_0.xci
# IP: The module: 'MicroBlaze_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Learn/robotdreams/Homework_004/MicroBlaze/MicroBlaze.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_mdm_1_0/MicroBlaze_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Learn/robotdreams/Homework_004/MicroBlaze/MicroBlaze.gen/sources_1/bd/MicroBlaze/ip/MicroBlaze_mdm_1_0/MicroBlaze_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
