# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Learn/robotdreams/Homework_004/Zynq_PS/Zynq_PS.srcs/sources_1/bd/zynq_PS/ip/zynq_PS_processing_system7_0_0/zynq_PS_processing_system7_0_0.xci
# IP: The module: 'zynq_PS_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Learn/robotdreams/Homework_004/Zynq_PS/Zynq_PS.gen/sources_1/bd/zynq_PS/ip/zynq_PS_processing_system7_0_0/zynq_PS_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_PS_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Learn/robotdreams/Homework_004/Zynq_PS/Zynq_PS.srcs/sources_1/bd/zynq_PS/ip/zynq_PS_processing_system7_0_0/zynq_PS_processing_system7_0_0.xci
# IP: The module: 'zynq_PS_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Learn/robotdreams/Homework_004/Zynq_PS/Zynq_PS.gen/sources_1/bd/zynq_PS/ip/zynq_PS_processing_system7_0_0/zynq_PS_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_PS_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
